App_Login/urls.py
from django.urls import path
from . import views


app_name = "App_Login"

urlpatterns = [
    path("create_profile/", views.create_profile, name="create_profile"),
    path('login/', views.login_profile, name="login_profile"),
    path('logout/', views.logout_profile, name="logout_profile"),
    path('profile/', views.profile, name="profile"),
    path('change_profile/', views.change_profile, name="change_profile"),
    path('password/', views.change_pass, name="change_pass"),
    path('profile_pic/', views.add_pro_pic, name="add_pro_pic"),
    path('change_pro_pic/', views.change_pro_pic, name='change_pro_pic')
]

App_Video/urls.py
from django.urls import path
from . import views

app_name = 'App_Video'

urlpatterns = [
    path('', views.VideoList.as_view(), name='video_list'),
    path('upload/', views.UploadVideo.as_view(), name='upload_video'),
    path('play/<slug>', views.play_video, name='play_video'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('category/<str:category>/', views.CategoryList, name='category_list'),
    path('my-videos/', views.MyVideos.as_view(), name='my_videos'),
    path('edit/<pk>/', views.UpdateVideo.as_view(), name='update_video'),
    path('search/', views.search_list, name='search_list'),

]

muslim_shows/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("App_Login.urls")),
    path('video/', include("App_Video.urls")),
    path('', views.Index, name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Video/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

category_choices = (
    ("Quran", "Quran"),
    ("Hadith", "Hadith"),
    ("Fiqh", "Fiqh"),
    ("Heart Softener", "Heart Softener"),
    ("Biography", "Biography"),
    ("Debate", "Debate"),
    ("Dawah", "Dawah")
)

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Video(models.Model):
    uploader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='video_uploader')
    video_title = models.CharField(
        max_length=255, verbose_name="Title for your video")
    slug = models.SlugField(max_length=264, unique=True)
    video_link = models.URLField(max_length=264, unique=False)
    video_description = models.TextField(verbose_name="Video description")
    category = models.CharField(
        max_length=255, choices=category_choices, default='Islamic')
    video = models.FileField(upload_to='video-files', verbose_name='video',
                             validators=[FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])
    video_thumb = models.ImageField(
        upload_to='video_thumbs', verbose_name='thumb')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date']

    def __str__(self):
        return self.video_title


class Comment(models.Model):
    video = models.ForeignKey(
        Video, on_delete=models.CASCADE, related_name='video_comment')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']

    def __str__(self):
        return self.comment


class Like(models.Model):
    video = models.ForeignKey(
        Video, on_delete=models.CASCADE, related_name='liked_video')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='liker_user')

    def __str__(self):
        return str(self.user) + " likes " + str(self.video)

App_Video/forms.py
from django import forms
from App_Video.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Video/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from App_Video.models import Video, Comment, Like
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from App_Video.forms import CommentForm
import uuid

# Create your views here.


class UploadVideo(LoginRequiredMixin, CreateView):
    model = Video
    template_name = 'App_Video/upload_video.html'
    fields = ('video_title', 'video_link', 'video',
              'video_thumb', 'video_description', 'category')

    def form_valid(self, form):
        form_obj = form.save(commit=False)
        form_obj.uploader = self.request.user
        title = form_obj.video_title
        form_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        form_obj.save()
        return HttpResponseRedirect(reverse('index'))


class VideoList(ListView):
    context_object_name = 'videos'
    model = Video
    template_name = 'App_Video/video_list.html'


def CategoryList(request, category):
    videos = Video.objects.filter(category=category)
    return render(request, 'App_Video/category_list.html', context={'videos': videos, 'category': category})


def search_list(request):
    if request.method == "POST":
        searched = request.POST['searched']
        videos = Video.objects.filter(video_title__contains=searched)
        return render(request, "App_Video/search_list.html", context={'searched': searched, 'videos': videos})

    else:
        return render(request, "App_Video/search_list.html", context={})


class MyVideos(LoginRequiredMixin, TemplateView):
    template_name = 'App_Video/my_videos.html'


@login_required
def play_video(request, slug):
    video = Video.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Like.objects.filter(video=video, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.video = video
            comment.save()
            return HttpResponseRedirect(reverse('App_Video:play_video', kwargs={'slug': slug}))
    return render(request, 'App_Video/play_video.html', context={'video': video, 'comment_form': comment_form, 'liked': liked, })


@login_required
def liked(request, pk):
    video = Video.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(video=video, user=user)
    if not already_liked:
        liked_post = Like(video=video, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Video:play_video', kwargs={'slug': video.slug}))


@login_required
def unliked(request, pk):
    video = Video.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(video=video, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Video:play_video', kwargs={'slug': video.slug}))


class UpdateVideo(LoginRequiredMixin, UpdateView):
    model = Video
    fields = ('video_title', 'video_link', 'video',
              'video_thumb', 'video_description', 'category')
    template_name = 'App_Video/update_video.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Video:play_video', kwargs={'slug': self.object.slug})

templates/App_Video/category_list.html
{% extends 'base.html' %}
{% block title_block %} Islamic Lectures {% endblock %}
{% block body_block %}
<h2>Videos in "{{category}}" category</h2>
<hr>
<br>
{% for video in videos %}
<h5>{{video.video_title}}</h5>
<h6><i>{{video.publish_date}}</i></h6>
<div class="row">
    <div class="col-sm-8">
        <a href="{% url 'App_Video:play_video' slug=video.slug %}"><img src="/media/{{video.video_thumb}}"
                alt="{{video.video_title}}" title="{{video.video_title}}" width="100%">
        </a>
    </div>
    <div class="col-sm-4">
        <h6>{{video.liked_video.count}} Likes | {{video.video_comment.count}} Comments </h6>
        <h6>Posted By: {{video.uploader}}</a></h6>
    </div>
</div>
<hr>
{% endfor %}
{% endblock %}

templates/App_Video/my_videos.html
{% extends 'base.html' %}
{% block title_block %} {{user}} {% endblock %}
{% block body_block %}
{% for video in user.video_uploader.all %}
<h3>{{video.video_title}}</h3>
<h6>{{video.publish_date}}</h6>
<div class="container">

    <div class="col-sm-6">
        <a href="{% url 'App_Video:play_video' slug=video.slug %}">
            <img src="/media/{{video.video_thumb}}" width="100%"></a>
    </div>
    <a href="{% url 'App_Video:update_video' pk=video.pk %}">Update Video</a>

</div>

<hr>
{% endfor %}
{% endblock %}

templates/App_Video/play_video.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title_block %}
{{video.video_title}} {% endblock %} {% block body_block %}

<div class="container">
   <video
      width="100%"
      max-width="720px"
      controls
      poster="/media/{{video.video_thumb}}">
      <source src="/media/{{video.video}}" type="video/mp4" />
   </video>
   <h4>{{video.video_title}}</h4>
   <h6>{{video.uploader}} | <i>{{video.publish_date}}</i></h6>
   <p>
      {{video.liked_video.count}} Likes | {{video.video_comment.count}} Comments
   </p>

   {% if not liked %}
   <a href="{% url 'App_Video:liked_post' pk=video.pk %}">
      <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
   </a>
   {% else %}
   <a href="{% url 'App_Video:unliked_post' pk=video.pk %}">
      <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
   </a>
   {% endif %}
   <br />
   <hr />
   <h6>Video desciption</h6>
   <div class="overflow-scroll" style="height: 150px">
      <p>{{video.video_description|linebreaks}}</p>
   </div>
   <div>
      <form method="POST">
         {{ comment_form|crispy }} {% csrf_token %}
         <button type="submit" class="btn btn-primary btn-sm">Comment</button>
      </form>
   </div>
   <div class="overflow-scroll">
      <hr />
      <h5>Comments:</h5>
      {% for comment in video.video_comment.all %}
      <p>
         <a href="#">@ <b>{{comment.user}}</b></a> {{comment.comment}}
      </p>
      <p>{{comment.comment_date}}</p>
      {% endfor %}
   </div>
   <br />
</div>

{% endblock %}

templates/App_Video/search_list.html
{% extends 'base.html' %}
{% block title_block %} Islamic Lectures {% endblock %}
{% block body_block %}


{% if searched %}
    {% if videos %}
        <h2>You searched for... {{searched}}</h2><hr><br>

        {% for video in videos %}
        <h3>{{video.video_title}}</h3>
        <h6><i>{{video.publish_date}}</i></h6>
        <div class="row">
            <div class="col-sm-8">
                <a href="{% url 'App_Video:play_video' slug=video.slug %}"><img src="/media/{{video.video_thumb}}"
                        alt="{{video.video_title}}" title="{{video.video_title}}" width="100%">
                </a>
            </div>
            <div class="col-sm-4">
                <h6>{{video.liked_video.count}} Likes | {{video.video_comment.count}} Comments | <a
                        href="{% url 'App_Video:category_list' category=video.category %}">{{video.category}}</a></h6>
                <h6>Posted By: {{video.uploader}}</a></h6>
            </div>
        </div>
        <hr>
        {% endfor %}

    {% else %}
        <h2>No related video found. Search for something else.</h2>
    {% endif %}

{% else %}
    <h2>You didn't search anything</h2>
{% endif %}

{% endblock %}

templates/App_Video/update_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{video.video_title}} {% endblock %}
{% block body_block %}
{% if video.uploader == user %}
<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" name="button">Update</button>
    {% else %}
    <p>Your are not allowed to view this page. 404</p>
</form>
{% endif %}
{% endblock %}

templates/App_Video/upload_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Upload your video {% endblock %}
{% block body_block %}
<h2>Upload Your Video Here:</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
{% endblock %}

templates/App_Video/video_list.html
{% extends 'base.html' %}
{% block title_block %} Islamic Lectures {% endblock %}
{% block body_block %}
{% for video in videos %}
<h3>{{video.video_title}}</h3>
<h6><i>{{video.publish_date}}</i></h6>
<div class="row">
    <div class="col-sm-8">
        <a href="{% url 'App_Video:play_video' slug=video.slug %}"><img src="/media/{{video.video_thumb}}"
                alt="{{video.video_title}}" title="{{video.video_title}}" width="100%">
        </a>
    </div>
    <div class="col-sm-4">
        <h6>{{video.liked_video.count}} Likes | {{video.video_comment.count}} Comments</h6>
        <h5><a
            href="{% url 'App_Video:category_list' category=video.category %}">{{video.category}}</a></h5>
        <h6>Posted By: {{video.uploader}}</a></h6>
    </div>
</div>
<hr>
{% endfor %}
{% endblock %}