App_Login/urls.py
from django.urls import path
from . import views


app_name = "App_Login"

urlpatterns = [
    path("create_profile/", views.create_profile, name="create_profile"),
    path('login/', views.login_profile, name="login_profile"),
    path('logout/', views.logout_profile, name="logout_profile"),
    path('profile/', views.profile, name="profile"),
    path('change_profile/', views.change_profile, name="change_profile"),
    path('password/', views.change_pass, name="change_pass"),
    path('profile_pic/', views.add_pro_pic, name="add_pro_pic"),
    path('change_pro_pic/', views.change_pro_pic, name='change_pro_pic')
]

muslim_shows/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("App_Login.urls")),
    path('video/', include("App_Video.urls")),
    path('', views.Index, name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, related_name="user_profile", on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

    def __str__(self):
        return self.user.username + "'s profile pic ---> " + (str(self.profile_pic)).split("/")[1]

App_Login/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from App_Login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic
# Create your views here.


def create_profile(request):
    form = SignUpForm()
    registered = False
    if request.method == "POST":
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
    diction = {'form': form, 'registered': registered}
    return render(request, "App_Login/create_profile.html", context=diction)


def login_profile(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
    return render(request, "App_Login/login.html", context={'form': form})


@login_required
def logout_profile(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


@login_required
def profile(request):
    return render(request, "App_Login/profile.html", context={})


@login_required
def change_profile(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(data=request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
            return HttpResponseRedirect(reverse("App_Login:profile"))
    return render(request, "App_Login/change_profile.html", context={'form': form})


@login_required
def change_pass(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
            return HttpResponseRedirect(reverse("App_Login:change_profile"))
    return render(request, "App_Login/change_pass.html", context={'form': form, 'changed': changed})


@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == "POST":
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse("App_Login:profile"))
    return render(request, "App_Login/pro_pic_add.html", context={'form': form})


@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == "POST":
        form = ProfilePic(request.POST, request.FILES,
                          instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, "App_Login/pro_pic_add.html", context={'form': form})

templates/App_Login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Change Password
{% endblock  %}
{% block body_block %}
{% if changed %}
<div class="alert alert-success">Password changed successfully</div>
{% else %}
<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Change Password</button>
</form>
{% endif %}

{% endblock body_block %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Change profile
{% endblock  %}
{% block body_block %}

{% if registered %}
<div class="alert alert-success">Profile changed successfully</div>
{% else %}

<h2>Create New Account:</h2>
<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Create Account</button>
</form>

{% endif %}
{% endblock body_block %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Login
{% endblock title_block %}
{% block body_block %}
<form method="post">
    {{form|crispy}}
    {% csrf_token %}
    <input type="submit" class="btn-lg btn-success">
</form>
{% endblock body_block %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Add your profile picture
{% endblock  %}
{% block body_block %}
<form method="post" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Add</button>
</form>

{% endblock body_block %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title_block %}
Your Profile
{% endblock title_block %}
{% block body_block %}
<h2>Your Profile</h2>

{% if user.user_profile %}
<div class="container text-center">
    <img src="/media/{{user.user_profile.profile_pic}}" width="200px" class="rounded-circle" alt="pro pic">
    <br><br>
    <a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change profile pic</a>
</div>
{% else %}
<div class="container text-center">
    <img src="/media/profile_pics/avatar.jpg" width="200px" class="rounded-circle" alt="pro pic">
    <br><br>
    <a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change profile pic</a>
</div>
{% endif %}

<table class="table">
    <tr>
        <td>Username: <b>{{user.username}}</b></td>
    </tr>
    <tr>
        <td>Email: <em>{{user.email}}</em></td>
    </tr>
    <tr>
        <td>Name: {{user.first_name}} {{user.last_name}}</td>
    </tr>
</table>
<button class="btn btn-warning"><a href="{% url 'App_Login:change_profile' %}">Change Profile</a></button>
{% endblock body_block %}