App_Login/urls.py
from django.urls import path
from . import views


app_name = "App_Login"

urlpatterns = [
    path("create_profile/", views.create_profile, name="create_profile"),
    path('login/', views.login_profile, name="login_profile"),
    path('logout/', views.logout_profile, name="logout_profile"),
    path('profile/', views.profile, name="profile"),
    path('change_profile/', views.change_profile, name="change_profile"),
    path('password/', views.change_pass, name="change_pass"),
    path('profile_pic/', views.add_pro_pic, name="add_pro_pic"),
    path('change_pro_pic/', views.change_pro_pic, name='change_pro_pic')
]

App_Video/urls.py
from django.urls import path
from . import views

app_name = 'App_Video'

urlpatterns = [
    path('', views.VideoList.as_view(), name='video_list'),
    path('upload/', views.UploadVideo.as_view(), name='upload_video'),
    path('play/<slug>', views.play_video, name='play_video'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('category/<str:category>/', views.CategoryList, name='category_list'),
    path('my-videos/', views.MyVideos.as_view(), name='my_videos'),
    path('edit/<pk>/', views.UpdateVideo.as_view(), name='update_video'),
    path('search/', views.search_list, name='search_list'),

]

muslim_shows/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("App_Login.urls")),
    path('video/', include("App_Video.urls")),
    path('', views.Index, name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- Font Awesome -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

        <title>{% block title_block %} Islamic Lectures {% endblock %} </title>
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'index' %}"><img
                                    src="/media/logo.jpg" alt="Home" width="30px"></a>
                        </li>

                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'App_Video:upload_video' %}">Upload
                                Video</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'App_Video:my_videos' %}">My
                                Videos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'App_Login:profile' %}">My
                                Profile</a></li>
                        <hr>
                        <li class="nav-item"><a class="nav-link" href="{% url 'App_Login:logout_profile' %}">logout</a>
                        </li>
                        <li class="nav-link disabled">@{{user.username}}</a></li>


                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'App_Login:create_profile' %}">sign
                                up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'App_Login:login_profile' %}">login</a>
                        </li>
                        {% endif %}

                    </ul>
                    <form class="d-flex" role="search" method="POST" action="{% url 'App_Video:search_list' %}">
                        <input class="form-control me-2" type="search" placeholder="Search Videos" aria-label="Search"
                            name="searched">
                        <button class="btn btn-outline-secondary" type="submit">Search</button>
                        {% csrf_token %}
                    </form>

                </div>
            </div>
        </nav>

        <div class="container" style="padding-top: 20px;">
            {% block body_block %}

            {% endblock body_block %}

        </div>

        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>


    </body>

</html>